### PR TITLE
Related to issue #38

### PR DESCRIPTION
**Pull request by LuisOlivaresJ**
A new line of code to automatically create a new release on GutHub **only if** the pull request merge branch has a tag.
To test, the branch "issue_action_workflow" (from where I am opening this pull request) has a tag on it.

### CODE REVIEW

**Comment by LuisOlivaresJ** [comment]
Hi, I would like to add that we need a tag because otherwise the workflow is going to take the name of the branch (OMG_master) to name the release, and since it already exists (from the last release), we get an error. ``github.ref`` is the variable used by the workflow to get the release name that is going to be used, as can be see [here](https://docs.github.com/en/actions/learn-github-actions/contexts). Additionally, I am considering to delete the tag named "OMG_master" to avoid confusion with the master branch name. What do you think?

Tag

**Comment by jfcabana** [comment]
> Hi, I would like to add that we need a tag because otherwise the workflow is going to take the name of the branch (OMG_master) to name the release, and since it already exists (from the last release), we get an error. `github.ref` is the variable used by the workflow to get the release name that is going to be used, as can be see [here](https://docs.github.com/en/actions/learn-github-actions/contexts). Additionally, I am considering to delete the tag named "OMG_master" to avoid confusion with the master branch name. What do you think?
> 
> Tag

I agree with the suggestion.

**Review by jfcabana — APPROVED** [review]

**Comment by LuisOlivaresJ** [comment]
can not detele the tag

I can not delete the OMG_master tag. Maybe because repository permissions.

**Comment by jfcabana** [comment]
> can not detele the tag
> 
> I can not delete the OMG_master tag. Maybe because repository permissions.

I could not delete either. I could however Edit Release and change the tag to v1.6.1.

**Comment by LuisOlivaresJ** [comment]
That could be enough. Now, let's see what happens with this pull request.

**Pull request merged**
