### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by LuisOlivaresJ**
An attempt to trigger the workflow run to publish on PyPi. I have a tag in this [commit](7cbdbecd8ac5a9081afdf5939647971ba8a49c9c)

### CODE REVIEW

**Comment by jfcabana** [comment]
I setup the build/publish to pypi to be triggered on tag pushes, but only on the master branch. 
All other push activity, on any branch, should trigger a publish on testpypi only.

**Comment by jfcabana** [comment]
I'm not sure if it applies to tag pushed on another branch, and then merge into master. Let's see what happens. For now I can see on testpypi that it has been updated.
image

**Review by jfcabana — APPROVED** [review]

**Comment by jfcabana** [comment]
The way I allowed only tag pushes to master to publish to pypi is via environment protection rules on the pypi environment. Maybe a better way would be to filter it directly in the workflows yaml file. As of now, it shows up as an error in the publish action.
image

**Comment by LuisOlivaresJ** [comment]
As you said, it's something related with environment protection rules. I am not familiar with that but I'll investigate. 

Captura

**Comment by jfcabana** [comment]
I set that up myself thinking it was the way to go, but now I'm not so sure. I can fix that.

**Comment by jfcabana** [comment]
I removed the environment protection rule now. We should decide on what is the best practice for deployment. For now, everything that is pushed is getting built and deployed on test.pypi. Not sure if that needs to be. Every tag push gets triggers a build and publish on pypi. Not quite sure if that's the best way, or should it be limited to tag pushes, or any push, on the master branch only. What do you think?

**Comment by LuisOlivaresJ** [comment]
That's a good question. For now I think it's ok to allow trigger to publish on PyPi only on tag pushes. Did you figure out if it applies to tag pushed on another branch, and trigger when merge into master?

**Comment by jfcabana** [comment]
That does not seem to be the case. I just merge your pull request, and the workflow shows that the actions of publishing to pypi have been skipped. From now on every tag push should work though.
image

**Comment by LuisOlivaresJ** [comment]
I think that the skip was because you made a merge (not a pull) so the action did not get trigger.

**Pull request merged**
